FROM dreg.cloud.sdu.dk/ucloud-apps/base-debian:TAG

LABEL course="" \
      author="" \
      description=""

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER 0

ENV HOME=/home/$USER

WORKDIR ${HOME}

## Add entrypoint script
COPY --chown=$USER:$USER  start_app.sh /usr/bin/start_course
RUN chmod 755 /usr/bin/start_course

USER ${USERID}

WORKDIR /work
