FROM dreg.cloud.sdu.dk/ucloud-apps/base-ubuntu:TAG

LABEL course="" \
      author="" \
      description=""

## Use bash instead of sh
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER 0

WORKDIR /home/$USER

USER ${USERID}

## Add entrypoint script
COPY --chown=$USER:$USER  start_course.sh /usr/bin/start_course
RUN chmod 755 /usr/bin/start_course

WORKDIR /work
