ARG TAG

FROM dreg.cloud.sdu.dk/ucloud-apps/conda:TAG

LABEL course="" \
      author="" \
      description=""

## Use bash instead of sh
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER 0

USER $USERID

## Add entrypoint script
COPY --chown=${USERID}:${GROUPID}  start_app /usr/bin/start_app
RUN chmod 755 /usr/bin/start_app

WORKDIR /work

