ARG TAG

FROM dreg.cloud.sdu.dk/ucloud-apps/jupyter-base:TAG

MAINTAINER ""

LABEL course="" \
      author="" \
      version="" \
      license="" \
      description=""

ENV REFRESHED_AT 2023-04-14

USER 0

WORKDIR /home/$NB_USER

USER $NB_UID

## Add entrypoint script
COPY --chown="${NB_USER}":"${NB_GID}" start_app.sh /usr/bin/start_app
RUN chmod 755 /usr/bin/start_app

WORKDIR /work
