FROM dreg.cloud.sdu.dk/ucloud-apps/rstudio:TAG

LABEL course="" \
      author="" \
      description=""

## Use bash instead of sh
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER 0

USER ${USERID}

WORKDIR /home/${USER}

## Add entrypoint script
COPY --chown=${USERID}:${GROUPID} start_course.sh /usr/bin/start_course
RUN chmod 755 /usr/bin/start_course

WORKDIR /work
