FROM dreg.cloud.sdu.dk/ucloud-apps/base-almalinux:TAG

LABEL Course="" \
      author="" \
      description=" " 

USER 0

## Use bash instead of sh
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER 0

ENV HOME=/home/$USER

WORKDIR ${HOME}

USER ${USERID}

## Add entrypoint script
COPY --chown=$USER:$USER  start_app.sh /usr/bin/start_course
RUN chmod 755 /usr/bin/start_course

WORKDIR /work
